- name: Create Azure VM
  hosts: localhost
  connection: local
  vars:
    resource_group: ansible
    webapp_name: tx-dot-net-project-demo
    location: centalindia
  tasks:
    - name: Create a dotnetcore WebApp
      azure_rm_webapp:
        resource_group: "{{ resource_group }}"
        name: "{{ webapp_name }}"
        plan:
          resource_group: "{{ resource_group }}"
          name: myDotnetappplan
          is_linux: false
          sku: S1
          number_of_workers: 1
        frameworks:
          - name: "net_framework"
            version: "5.0"
