- name: Create Azure VM
  hosts: localhost
  connection: local
  vars:
    resource_group: "{{ lookup('env', 'RES_GROUP') }}"
    webapp_name: demo-dot-net-project
    location: eastus
  tasks:
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"
    - name: Create a dotnetcore WebApp
      azure_rm_webapp:
        resource_group: "{{ resource_group }}"
        name: "{{ webapp_name }}"
        plan:
          resource_group: "{{ resource_group }}"
          name: myDotappplan
          is_linux: false
          sku: S1
          number_of_workers: 1
        frameworks:
          - name: "net_framework"
            version: "3.5"
